title: Saketh Sarangu
#logo: /assets/img/pic.png 
description: A highly motivated data professional with expertise in interpreting, analyzing and reconciliation of data
obtained from a variety of sources
show_downloads: true
theme: jekyll-theme-minimal
